function fnMap(){}
function fnFilter(){}
function fnForEach(){}
function fnFind(){}
function fnSort(){}
function fnSome(){}
function fnEvery(){}
function fnConcat(){}
function fnIncludes(){}
function fnJoin(){}
function fnReduce(){}
function fnIndexOf(){}
function fnFindeIndex(){}
function fnFill(){}
function fnPush(){}
function fnPop(){}
function fnShift(){}
function fnUnshift(){}
function fnSlice(){}
function fnReverse(){}
function fnSplice(){}
function fnLastIndexOf(){}
function fnFlat(){}
function fnIsArray(){}
function fnFrom(){}